.TH "Analysis.h" 3 "Fri Apr 24 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Analysis.h \- Spectral \fBAnalysis\fP\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include 'WAVData\&.h'\fP
.br
\fC#include <math\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAnalysis\fP"
.br
.RI "Spectral \fBAnalysis\fP\&. "
.in -1c
.SH "Detailed Description"
.PP 
Spectral \fBAnalysis\fP\&. 

Spectral analysis include functions: DFT, IDFT\&. Significant components such as the power spectrum and the phase of signal are obtained\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
