.TH "CheckData.h" 3 "Fri Apr 24 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CheckData.h \- Check input data\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCheckData\fP"
.br
.RI "Check input value\&. "
.in -1c
.SH "Detailed Description"
.PP 
Check input data\&. 

Input data is checked, including file names and the parameters for performing the functions 
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
