.TH "Enhancement.h" 3 "Fri Apr 24 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Enhancement.h \- Speech \fBEnhancement\fP\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'Analysis\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBEnhancement\fP"
.br
.RI "Speech enhancement\&. "
.in -1c
.SH "Detailed Description"
.PP 
Speech \fBEnhancement\fP\&. 

Speech enhancement such as spectral subtraction and the Wiener filter are included and implemented in the class, which is derived from the class \fBAnalysis\fP 
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
