.TH "Simulation.h" 3 "Fri Apr 24 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Simulation.h \- Noisy Speech \fBSimulation\fP\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include 'WAVData\&.h'\fP
.br
\fC#include <math\&.h>\fP
.br
\fC#include 'IO\&.h'\fP
.br
\fC#include 'RunMenu\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSimulation\fP"
.br
.RI "Noise simulation\&. "
.in -1c
.SH "Detailed Description"
.PP 
Noisy Speech \fBSimulation\fP\&. 

Header file for noisy speech simulation Include two ways for implementation
.IP "1." 4
Add Gaussian white noise to clean speech
.IP "2." 4
Add noisy file to clean speech file 
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
