.TH "TWAVData" 3 "Fri Apr 24 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TWAVData
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBload\fP (char *name, bool header_only=false)"
.br
.ti -1c
.RI "void \fBwrite\fP (char *name)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBTRIFF\fP * \fBhdr\fP"
.br
.ti -1c
.RI "unsigned int \fBnSamples\fP"
.br
.ti -1c
.RI "short int * \fBSample\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
